backend:
  name: git-gateway
  branch: main # or "master", depending on your repo

media_folder: "images" # Where uploaded files go in repo
public_folder: "/images" # How images are referenced in code

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "officers.json"
        label: "Officers"
        name: "officers"
        fields:
          - name: "officers"
            label: "Officers"
            widget: "list"
            fields:
              - { name: "name", label: "Name", widget: "string" }
              - { name: "role", label: "Role", widget: "string" }
              - { name: "photo", label: "Photo", widget: "image" }
